### ISSUE TITLE
Removing a metric update the last report time

### ISSUE THREAD

**Issue by QuentinLemCode** [cherrypush/cherrypush.com#380]
Hello

When removing a metric, the last report time on the projects list page is updated

I have removed some metrics but didn't pushed any new report
<img width="335" alt="image" src="https://github.com/user-attachments/assets/66f4c1e2-3388-43d7-a8dd-d9b120b0e0fd">

**Comment by fwuensche** [comment]
Well spotted. I've just fixed this here: https://github.com/cherrypush/cherrypush.com/pull/382
Also moved the button to the top and added a confirmation before deleting projects.
Thanks for all the suggestions 👍
