### ISSUE TITLE
Allow custom path to CODEOWNERS 

### ISSUE THREAD

**Issue by fwuensche** [cherrypush/cherrypush.com#39]
If a project has its CODEOWNERS file nested inside a subfolder, the Cherry CLI won't automatically detect it. 

We could either: 

- automatically look for CODEOWNERS in folders and subfolders
- allow a custom path for CODEOWNERS on .cherry.js

**Comment by Djiit** [comment]
See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-file-location for common locations

**Comment by fwuensche** [comment]
This issue concerns the CLI, and I didn't have any other report since then. I'm closing it for now, but we can always reopen it (in the CLI project) if it becomes a real issue for someone using Cherry.
